[package]
name = "snippet_storage"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.5"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.42.0" }
assert_macros = "2.8.5"


[[target.starknet-contract]]
casm = true
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.fmt]
sort-module-level-items = true
